FROM golang:1.23.1-alpine
RUN apk add --no-cache git bash

RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /usr/src/app
COPY . .
RUN go mod vendor
EXPOSE 2345
CMD ["dlv", "debug", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient", "--", "$GOFILE"]
